package com.gusfot.pray.dao;

import com.gusfot.pray.model.Moim;
import com.gusfot.pray.model.MoimExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MoimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int countByExample(MoimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int deleteByExample(MoimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int deleteByPrimaryKey(Integer moimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int insert(Moim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int insertSelective(Moim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    List<Moim> selectByExample(MoimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    Moim selectByPrimaryKey(Integer moimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int updateByExampleSelective(@Param("record") Moim record, @Param("example") MoimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int updateByExample(@Param("record") Moim record, @Param("example") MoimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int updateByPrimaryKeySelective(Moim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moim
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int updateByPrimaryKey(Moim record);
}