package com.gusfot.pray.dao;

import com.gusfot.pray.model.Pray;
import com.gusfot.pray.model.PrayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int countByExample(PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int deleteByExample(PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int deleteByPrimaryKey(Integer prayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int insert(Pray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int insertSelective(Pray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    List<Pray> selectByExample(PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    Pray selectByPrimaryKey(Integer prayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int updateByExampleSelective(@Param("record") Pray record, @Param("example") PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int updateByExample(@Param("record") Pray record, @Param("example") PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int updateByPrimaryKeySelective(Pray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    int updateByPrimaryKey(Pray record);
}