package com.gusfot.pray.model;

import java.util.Date;

public class Moim {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moim.moim_id
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    private Integer moimId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moim.name
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moim.reg_user_id
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    private Integer regUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moim.reg_time
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    private Date regTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moim.moim_id
     *
     * @return the value of moim.moim_id
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public Integer getMoimId() {
        return moimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moim.moim_id
     *
     * @param moimId the value for moim.moim_id
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public void setMoimId(Integer moimId) {
        this.moimId = moimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moim.name
     *
     * @return the value of moim.name
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moim.name
     *
     * @param name the value for moim.name
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moim.reg_user_id
     *
     * @return the value of moim.reg_user_id
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public Integer getRegUserId() {
        return regUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moim.reg_user_id
     *
     * @param regUserId the value for moim.reg_user_id
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public void setRegUserId(Integer regUserId) {
        this.regUserId = regUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moim.reg_time
     *
     * @return the value of moim.reg_time
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moim.reg_time
     *
     * @param regTime the value for moim.reg_time
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}