package com.gusfot.pray.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PrayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public PrayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrayIdIsNull() {
            addCriterion("pray_id is null");
            return (Criteria) this;
        }

        public Criteria andPrayIdIsNotNull() {
            addCriterion("pray_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrayIdEqualTo(Integer value) {
            addCriterion("pray_id =", value, "prayId");
            return (Criteria) this;
        }

        public Criteria andPrayIdNotEqualTo(Integer value) {
            addCriterion("pray_id <>", value, "prayId");
            return (Criteria) this;
        }

        public Criteria andPrayIdGreaterThan(Integer value) {
            addCriterion("pray_id >", value, "prayId");
            return (Criteria) this;
        }

        public Criteria andPrayIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pray_id >=", value, "prayId");
            return (Criteria) this;
        }

        public Criteria andPrayIdLessThan(Integer value) {
            addCriterion("pray_id <", value, "prayId");
            return (Criteria) this;
        }

        public Criteria andPrayIdLessThanOrEqualTo(Integer value) {
            addCriterion("pray_id <=", value, "prayId");
            return (Criteria) this;
        }

        public Criteria andPrayIdIn(List<Integer> values) {
            addCriterion("pray_id in", values, "prayId");
            return (Criteria) this;
        }

        public Criteria andPrayIdNotIn(List<Integer> values) {
            addCriterion("pray_id not in", values, "prayId");
            return (Criteria) this;
        }

        public Criteria andPrayIdBetween(Integer value1, Integer value2) {
            addCriterion("pray_id between", value1, value2, "prayId");
            return (Criteria) this;
        }

        public Criteria andPrayIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pray_id not between", value1, value2, "prayId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTargetDateIsNull() {
            addCriterion("target_date is null");
            return (Criteria) this;
        }

        public Criteria andTargetDateIsNotNull() {
            addCriterion("target_date is not null");
            return (Criteria) this;
        }

        public Criteria andTargetDateEqualTo(Date value) {
            addCriterion("target_date =", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateNotEqualTo(Date value) {
            addCriterion("target_date <>", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateGreaterThan(Date value) {
            addCriterion("target_date >", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateGreaterThanOrEqualTo(Date value) {
            addCriterion("target_date >=", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateLessThan(Date value) {
            addCriterion("target_date <", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateLessThanOrEqualTo(Date value) {
            addCriterion("target_date <=", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateIn(List<Date> values) {
            addCriterion("target_date in", values, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateNotIn(List<Date> values) {
            addCriterion("target_date not in", values, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateBetween(Date value1, Date value2) {
            addCriterion("target_date between", value1, value2, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateNotBetween(Date value1, Date value2) {
            addCriterion("target_date not between", value1, value2, "targetDate");
            return (Criteria) this;
        }

        public Criteria andIsAchievedIsNull() {
            addCriterion("is_achieved is null");
            return (Criteria) this;
        }

        public Criteria andIsAchievedIsNotNull() {
            addCriterion("is_achieved is not null");
            return (Criteria) this;
        }

        public Criteria andIsAchievedEqualTo(String value) {
            addCriterion("is_achieved =", value, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedNotEqualTo(String value) {
            addCriterion("is_achieved <>", value, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedGreaterThan(String value) {
            addCriterion("is_achieved >", value, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedGreaterThanOrEqualTo(String value) {
            addCriterion("is_achieved >=", value, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedLessThan(String value) {
            addCriterion("is_achieved <", value, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedLessThanOrEqualTo(String value) {
            addCriterion("is_achieved <=", value, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedLike(String value) {
            addCriterion("is_achieved like", value, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedNotLike(String value) {
            addCriterion("is_achieved not like", value, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedIn(List<String> values) {
            addCriterion("is_achieved in", values, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedNotIn(List<String> values) {
            addCriterion("is_achieved not in", values, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedBetween(String value1, String value2) {
            addCriterion("is_achieved between", value1, value2, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andIsAchievedNotBetween(String value1, String value2) {
            addCriterion("is_achieved not between", value1, value2, "isAchieved");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeIsNull() {
            addCriterion("achieved_time is null");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeIsNotNull() {
            addCriterion("achieved_time is not null");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeEqualTo(Date value) {
            addCriterion("achieved_time =", value, "achievedTime");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeNotEqualTo(Date value) {
            addCriterion("achieved_time <>", value, "achievedTime");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeGreaterThan(Date value) {
            addCriterion("achieved_time >", value, "achievedTime");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("achieved_time >=", value, "achievedTime");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeLessThan(Date value) {
            addCriterion("achieved_time <", value, "achievedTime");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeLessThanOrEqualTo(Date value) {
            addCriterion("achieved_time <=", value, "achievedTime");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeIn(List<Date> values) {
            addCriterion("achieved_time in", values, "achievedTime");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeNotIn(List<Date> values) {
            addCriterion("achieved_time not in", values, "achievedTime");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeBetween(Date value1, Date value2) {
            addCriterion("achieved_time between", value1, value2, "achievedTime");
            return (Criteria) this;
        }

        public Criteria andAchievedTimeNotBetween(Date value1, Date value2) {
            addCriterion("achieved_time not between", value1, value2, "achievedTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeIsNull() {
            addCriterion("reg_time is null");
            return (Criteria) this;
        }

        public Criteria andRegTimeIsNotNull() {
            addCriterion("reg_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegTimeEqualTo(Date value) {
            addCriterion("reg_time =", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotEqualTo(Date value) {
            addCriterion("reg_time <>", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeGreaterThan(Date value) {
            addCriterion("reg_time >", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("reg_time >=", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeLessThan(Date value) {
            addCriterion("reg_time <", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeLessThanOrEqualTo(Date value) {
            addCriterion("reg_time <=", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeIn(List<Date> values) {
            addCriterion("reg_time in", values, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotIn(List<Date> values) {
            addCriterion("reg_time not in", values, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeBetween(Date value1, Date value2) {
            addCriterion("reg_time between", value1, value2, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotBetween(Date value1, Date value2) {
            addCriterion("reg_time not between", value1, value2, "regTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pray
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 08 18:41:36 KST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pray
     *
     * @mbggenerated Fri Jul 08 18:41:36 KST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}