package com.gusfot.pray.model;

import java.util.Date;

public class Pray {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pray.pray_id
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	private Integer prayId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pray.title
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pray.content
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	private String content;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pray.userId
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pray.target_date
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	private Date targetDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pray.is_achieved
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	private String isAchieved;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pray.achieved_time
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	private Date achievedTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pray.reg_time
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	private Date regTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pray.pray_id
	 * @return  the value of pray.pray_id
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public Integer getPrayId() {
		return prayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pray.pray_id
	 * @param prayId  the value for pray.pray_id
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public void setPrayId(Integer prayId) {
		this.prayId = prayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pray.title
	 * @return  the value of pray.title
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pray.title
	 * @param title  the value for pray.title
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pray.content
	 * @return  the value of pray.content
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pray.content
	 * @param content  the value for pray.content
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pray.userId
	 * @return  the value of pray.userId
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pray.userId
	 * @param userId  the value for pray.userId
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pray.target_date
	 * @return  the value of pray.target_date
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public Date getTargetDate() {
		return targetDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pray.target_date
	 * @param targetDate  the value for pray.target_date
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public void setTargetDate(Date targetDate) {
		this.targetDate = targetDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pray.is_achieved
	 * @return  the value of pray.is_achieved
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public String getIsAchieved() {
		return isAchieved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pray.is_achieved
	 * @param isAchieved  the value for pray.is_achieved
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public void setIsAchieved(String isAchieved) {
		this.isAchieved = isAchieved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pray.achieved_time
	 * @return  the value of pray.achieved_time
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public Date getAchievedTime() {
		return achievedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pray.achieved_time
	 * @param achievedTime  the value for pray.achieved_time
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public void setAchievedTime(Date achievedTime) {
		this.achievedTime = achievedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pray.reg_time
	 * @return  the value of pray.reg_time
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pray.reg_time
	 * @param regTime  the value for pray.reg_time
	 * @mbggenerated  Fri Jul 08 18:41:36 KST 2016
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

}
